---
when:
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}
  - event: [ pull_request, manual, tag]

steps:
  - name: build
    image: owncloudci/nodejs:20
    commands:
      - pnpm install
      - pnpm build
  - name: deploy-staging
    image: debian:latest
    environment:
      SSH_KEY:
        from_secret: ssh-key-staging
      REMOTE_HOST:
        from_secret: remote-host-staging
    when:
      event: push
      branch: ${CI_REPO_DEFAULT_BRANCH}
    commands:
      - apt-get update
      - apt-get install -y openssh-client rsync
      - mkdir -p $HOME/.ssh
      - ssh-keyscan -t rsa $REMOTE_HOST >> $HOME/.ssh/known_hosts
      - echo "$SSH_KEY" > "$HOME/.ssh/id_rsa"
      - chmod 0600 $HOME/.ssh/id_rsa
      - ls
      - pwd
      - rsync -a --exclude '.git' --delete ./build/ $REMOTE_HOST:/var/opencloud-docs
